// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3aCnoioEb5zPcZYe9LnJdsJI--Oj7FYo',
    appId: '1:5081472319:web:75829b6c4a29a8af99878a',
    messagingSenderId: '5081472319',
    projectId: 'housr-66a18',
    authDomain: 'housr-66a18.firebaseapp.com',
    storageBucket: 'housr-66a18.appspot.com',
    measurementId: 'G-CFTCTY0B14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArXM6vJS8S8qduXL64MLTnfgalt6Ja20g',
    appId: '1:5081472319:android:cb528bc6232fb5f899878a',
    messagingSenderId: '5081472319',
    projectId: 'housr-66a18',
    storageBucket: 'housr-66a18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBQfpnMz43GQJ9jTjyIExBQldCeUnlpaM',
    appId: '1:5081472319:ios:ea5012a5aba2bcd899878a',
    messagingSenderId: '5081472319',
    projectId: 'housr-66a18',
    storageBucket: 'housr-66a18.appspot.com',
    iosClientId: '5081472319-g432a1frltkbt1iula7c6dsgfn9p4iai.apps.googleusercontent.com',
    iosBundleId: 'com.example.housrApp',
  );
}
